# Site settings
title: Open Source Lab
email: your-email@domain.com
description: "This website is an open-source repository of builds and build instructions of different laboratory apparatus by students and faculty at UCLA and elsewhere."
baseurl: ""
url: "http://opensourcelaboratory.com"

# Build settings
markdown: kramdown
permalink: pretty
collections:
  projects:
    output: true